# Generated by Django 4.2.16 on 2025-06-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otpcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
