# Generated by Django 4.2.16 on 2025-06-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
