# Generated by Django 4.2.22 on 2025-06-15 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0002_user_is_verified_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('gen', models.CharField(max_length=20)),
                ('tech', models.CharField(max_length=50)),
                ('plmn', models.CharField(max_length=20)),
                ('lac', models.IntegerField()),
                ('rac', models.IntegerField()),
                ('tac', models.IntegerField()),
                ('cid', models.BigIntegerField()),
                ('freq_band', models.FloatField()),
                ('afrn', models.FloatField()),
                ('freq', models.FloatField()),
                ('rsrp', models.FloatField()),
                ('rsrq', models.FloatField()),
                ('rscp', models.FloatField()),
                ('ecno', models.FloatField()),
                ('rxlev', models.FloatField()),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='phone_number')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('cell_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polaris.cellinfo')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='phone_number')),
            ],
        ),
        migrations.CreateModel(
            name='DNSTest',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polaris.test')),
                ('time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HTTPDownloadTest',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polaris.test')),
                ('throughput', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HTTPUploadTest',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polaris.test')),
                ('throughput', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PingTest',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polaris.test')),
                ('latency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SMSTest',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polaris.test')),
                ('send_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WebTest',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polaris.test')),
                ('response_time', models.FloatField()),
            ],
        ),
    ]
