# Generated by Django 4.2.22 on 2025-06-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0003_cellinfo_test_dnstest_httpdownloadtest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinfo',
            name='afrn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='ecno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='freq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='freq_band',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='lac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='rac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='rscp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='rsrp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='rsrq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='rxlev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='tac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
